- name: Install system updates for RHEL systems
  yum:
   name: '*'
   state: latest
   update_cache: yes
       #cache_valid_time: 3600
  when:
   - ansible_os_family == "RedHat"
   - ansible_distribution == "RHEL"
